### ISSUE TITLE
chown -Rf nginx:nginx /var/www/html takes too long

### ISSUE THREAD

**Issue by nunofmendes** [richarvey/nginx-php-fpm#170]
I am trying out this docker image with a large website I have. I'm using linked volumes (-v) with z flag.  The total is around 25gb (it has uploaded files etc). 

Every time I start the container, and it runs the start.sh script, it hangs for a lot of time in this line:
chown -Rf nginx:nginx /var/www/html

It's strange because sometimes it just takes a few minutes, then it can take up to 1 hour.

I would understand that it would take long the first time to change the permissions. Shouldn't it be faster or skip this line at all when it just restarting?

Am I missing something about Docker? Is this a bug? What can I do to optimize this?

**Comment by richarvey** [comment]
This will be fixed in 1.3.4 with an extra flag
