### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by aleskinen** [richarvey/nginx-php-fpm#171]
Dockerfile slightly by removing expose command since I am running this behind swarm proxy and it preaks, if two containers is running in same port. Got complains avout group and user nginx existing, added deluser nginx before these. Then I added mkdir /var/cache/nginx/client_temp since otherwice nginx died. Now everything seems good, except that if i try to run php files I get 
FastCGI sent in stderr: "Access to the script '/var/www/html' has been denied (see security.limit_extensions)" while reading response header from upstream, client: 10.0.1.15, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "yhteisotest.tek.fi"

Any ideas how this can be solved?

**Comment by richarvey** [comment]
Make sure that directory is owned by the nginx user, it should be fine if you do this.

**Comment by aleskinen** [comment]
html files open, but php files do not:
/var/www/html # curl -i localhost:9000
curl: (7) Failed to connect to localhost port 9000: Connection refused
/var/www/html # curl -i 127.0.0.1:9000
curl: (7) Failed to connect to 127.0.0.1 port 9000: Connection refused

**Comment by aleskinen** [comment]
Works now, changed php-7.1-alpine Dockerfile --with-fpm-user=www-data --with-fpm-group=www-data --with-fpm-user=nginx --with-fpm-group=nginx
