### ISSUE TITLE
help !! how to activate postgresql driver so my website can connect to posgresql database

### ISSUE THREAD

**Issue by firmandev** [richarvey/nginx-php-fpm#174]
im docker newbie, im so confuse how to do that, because my database is posgresql

**Comment by dionysius** [comment]
I don't know. I had the same issue. Found oramirezo/nginx-php-fpm-pgsql which is based on this dockerfile, but it is 6 months old :(

**Comment by dionysius** [comment]
Just found a better way!

You need to enable scripts as described here: https://github.com/richarvey/nginx-php-fpm/blob/master/docs/scripting_templating.md
Maybe consider the layout docs for understanding: https://github.com/richarvey/nginx-php-fpm/blob/master/docs/repo_layout.md

So enable scripts by setting environment `RUN_SCRIPTS=1`
And the script I did looks like:
```bash
#!/usr/bin/env bash

apk add postgresql-dev postgresql-client
docker-php-ext-install pgsql
```

**Comment by firmandev** [comment]
thanks for the reply, i will try your solution and tell the result :) @dionysius

**Comment by firmandev** [comment]
i tried and ext was installed but how to activate it in php.ini, because my website still cannot communicate with posgresql database.


Fatal error: Uncaught Error: Call to undefined function pg_connect() in /var/www/html/index.php:2 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 2

**Comment by firmandev** [comment]
it works

thanks for you help :*
