### ISSUE TITLE
Feature request: Add option to use non-secure http with token.

### ISSUE THREAD

**Issue by valichek** [richarvey/nginx-php-fpm#183]
It fetches data only from https. For example, one can run internal dev gogs service with non-https urls. Now we need to overwrite `/run.sh` script when running docker

**Comment by richarvey** [comment]
Do you mean the URL used for git pull?

**Comment by valichek** [comment]
@richarvey yes

**Comment by richarvey** [comment]
I'll look at adding an --insecure flag

**Comment by marek-knappe** [comment]
I think nice fix for that and #192 will be giving user option to give exactly url for git - not guessing it as you have it now, but it could be not backward compatible
