### ISSUE TITLE
PHP Error Log to Docker Logs

### ISSUE THREAD

**Issue by djarbz** [richarvey/nginx-php-fpm#184]
From what I've read the all logs, NGINX and PHP, should be captured by docker and viewable by docker logs -f container_name
I am only seeing NGINX logs and no PHP logs.

I am using the current image as of 10/18/2017

**Comment by richarvey** [comment]
there may be a flag i need to tweak let me look into it

**Comment by richarvey** [comment]
this is now closed thanks for the PR

**Comment by djarbz** [comment]
Thank you, I'll give it a try!
