### ISSUE TITLE
Crontab in container

### ISSUE THREAD

**Issue by jpissin** [richarvey/nginx-php-fpm#191]
Cron does not start by default in the container, tests using Dockerfile were unsuccessful. Is it possible to have crontab running by default in the image?

**Comment by richarvey** [comment]
This is something we are unlikely to add. running another daemon in the image isn't great practice, instead look at running cron as a side car container or using tasks in kubernetes.

**Comment by ramonberrutti** [comment]
is there a crontab and folders (15min hours, etc..) one is calling geoip.
You can add code inside there or just edit crontab and add your line.
