### ISSUE TITLE
Redis extension is not included

### ISSUE THREAD

**Issue by RomanGalochkin** [richarvey/nginx-php-fpm#194]
PHP 7. Redis extension is not included by default setups.

**Comment by richarvey** [comment]
I'll push this into the next version you are right this should be standard

**Comment by hulkwan** [comment]
Can I only add extensions already in the container? So I can not freely add the PHP extensions I need in this container

**Comment by gl0bus** [comment]
Hi there,
if someone needs this ASAP, the following code should let you use the php redis extension:

``` docker
  RUN apk add autoconf gcc musl-dev make
  RUN pecl install igbinary
  RUN echo -e "extension=igbinary.so\nigbinary.compact_strings=On" > /usr/local/etc/php/conf.d/docker-php-ext-igbinary.ini
  RUN echo "yes" | pecl install redis
  RUN echo "extension=redis.so" > /usr/local/etc/php/conf.d/docker-php-ext-redis.ini
```

**Comment by srnfr** [comment]
I needed Redis extension, but also NFS client and TZData as well.
Here's how I did it :

```
RUN apk add --no-cache --update \
    redis \
    autoconf git g++ make \
    nfs-utils \
    tzdata \
  && pecl install redis \
  && docker-php-ext-enable redis \
  && rm -fr /var/cache/apk/*
```

Works fine. Hope this helps.
