### ISSUE TITLE
Http2 support ALPN

### ISSUE THREAD

**Issue by writetosalman** [richarvey/nginx-php-fpm#195]
Hello 

I wanted to ask if we can enable http2 by just editing the config file or something extra has to be done? There is no mention of http2 protocol in the entire help documents.

Thanks

**Comment by writetosalman** [comment]
Nevermind ALPN. Just use http2 in conf and it works fine in Chrome.

```

    listen 443 ssl http2;
    listen [::]:443 ssl http2 ipv6only=on;
```

**Comment by richarvey** [comment]
I may add this by default in a new release!
