### ISSUE TITLE
script generate file permission issue

### ISSUE THREAD

**Issue by geekstek** [richarvey/nginx-php-fpm#196]
For laravel example:
I need to run a artisan command to generate a file when application startup, but the file permission was root. 
I tried to su - nginx -c "php artisan generate", but nginx is nologin.
That can't fix by USER nginx, because the script will install some other apk, and run script.
Any idea? Thank you very much

**Comment by geekstek** [comment]
more over, I tried to install shadow apk to chsh nginx from nologin to bash, but no luck when install...

**Comment by richarvey** [comment]
have you tried running this without "su - nginx -c" what permission errors do you get?

**Comment by geekstek** [comment]
> nologin: this account is not available

**Comment by geekstek** [comment]
ok, I figure out a shortcut for this issue, but need to modify start.sh file (maybe not),
change the line 179 `adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx -u ${PUID} nginx`
mainly remove the `-S` , and run all the command with su - nginx -c "XXX XXX XXX".

**Comment by geekstek** [comment]
Or not to modify the start.sh,
write this 2 lines in a new script file.
```
deluser nginx
adduser -D -h /var/cache/nginx -s /sbin/nologin -G nginx nginx
```
