### ISSUE TITLE
How to install php-mongodb and php-redis?

### ISSUE THREAD

**Issue by guoyanjun5** [richarvey/nginx-php-fpm#198]
> 
/usr/local/bin/docker-php-ext-install mongodb
error: /usr/src/php/ext/mongodb does not exist

usage: /usr/local/bin/docker-php-ext-install [-jN] ext-name [ext-name ...]
   ie: /usr/local/bin/docker-php-ext-install gd mysqli
       /usr/local/bin/docker-php-ext-install pdo pdo_mysql
       /usr/local/bin/docker-php-ext-install -j5 gd mbstring mysqli pdo pdo_mysql shmop

if custom ./configure arguments are necessary, see docker-php-ext-configure

Possible values for ext-name:
bcmath bz2 calendar ctype curl dba dom enchant exif fileinfo filter ftp gd gettext gmp hash iconv imap interbase intl json ldap mbstring mcrypt mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline recode reflection session shmop simplexml snmp soap sockets spl standard sysvmsg sysvsem sysvshm tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip

Some of the above modules are already compiled into PHP; please check
the output of "php -i" to see which modules are already loaded.
>

**Comment by hulkwan** [comment]
how did you resove it？？？

**Comment by guoyanjun5** [comment]
@hulkwan 

Insert 119 lines behind the root dockerfile file:

`    pecl install redis && \
    pecl install mongodb && \
    docker-php-ext-enable redis xdebug mongodb && \
`
