### ISSUE TITLE
apk upgrade states apk-tools is OLD! ?

### ISSUE THREAD

**Issue by gateway** [richarvey/nginx-php-fpm#232]
I installed the latest build today and am testing this out to figure out if this works for what I need. I usually make it a habit to update any packages when I first run, mainly looking for security fixes but running the command seemed to fail.  Please note im coming from more CentOS and Ubuntu so still digging into BusyBox (Alpine Linux?) 

```bash-4.3# apk upgrade
WARNING: This apk-tools is OLD! Some packages might not function properly.
OK: 201 MiB in 81 packages
bash-4.3# uname -a
Linux bc1752190a35 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux
bash-4.3# ```

**Comment by ifollett** [comment]
edit your /etc/apk/repositories file to include:
- http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
- http://dl-cdn.alpinelinux.org/alpine/latest-stable/community

instead of a specific version number

**Comment by 84hero** [comment]
@ifollett who to edit /etc/apk/repositories ?

**Comment by ifollett** [comment]
@84hero you will need to use something like nano or vi to edit the file

**Comment by cjaoude** [comment]
this issue also shows up in `richarvey/nginx-php-fpm:php71`...it's crippled our dockerfile for this project. 

@ifollett you seem to know what's going on, any chance you could push a PR fix for this? 

we attempted your solution, (and also others, like `apk add -u apk-tools` type solution in dockerfile) but still the error appears. :/
