### ISSUE TITLE
Let's encrypt impossible

### ISSUE THREAD

**Issue by Creaprog** [richarvey/nginx-php-fpm#234]
Hello,

I have the problem with setup let's encrypt.

My docker-compose : 
version: '3.3'

services:

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./wp-content:/var/www/html/

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  
  redis:
    container_name: redis
    image: redis
    restart: always

  web:
    container_name: nginx
    image: richarvey/nginx-php-fpm:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './wp-content:/var/www/html:rw'
    environment:
      DOMAIN: 'ndd.com'
      GIT_EMAIL: 'mail@gmail.com'
      WEBROOT: '/var/www/html'
    restart: always

For installation let's encrypt, I write : 
`docker-compose exec web /usr/bin/letsencrypt-setup`

This command return : 
`nginx: stopped
nginx: ERROR (spawn error)`

These last logs with Nginx : 

nginx        | 2018-04-26 10:40:53,498 INFO exited: nginx (exit status 1; not expected)
nginx        | 2018-04-26 10:40:54,502 INFO spawned: 'nginx' with pid 53
nginx        | 2018/04/26 10:40:54 [emerg] 53#53: invalid parameter "https2" in /etc/nginx/sites-enabled/default-ssl.conf:3
nginx        | nginx: [emerg] invalid parameter "https2" in /etc/nginx/sites-enabled/default-ssl.conf:3
nginx        | 2018-04-26 10:40:54,519 INFO exited: nginx (exit status 1; not expected)
nginx        | 2018-04-26 10:40:56,528 INFO spawned: 'nginx' with pid 54
nginx        | 2018/04/26 10:40:56 [emerg] 54#54: invalid parameter "https2" in /etc/nginx/sites-enabled/default-ssl.conf:3
nginx        | nginx: [emerg] invalid parameter "https2" in /etc/nginx/sites-enabled/default-ssl.conf:3
nginx        | 2018-04-26 10:40:56,549 INFO exited: nginx (exit status 1; not expected)
nginx        | 2018-04-26 10:40:59,557 INFO spawned: 'nginx' with pid 55
nginx        | 2018/04/26 10:40:59 [emerg] 55#55: invalid parameter "https2" in /etc/nginx/sites-enabled/default-ssl.conf:3
nginx        | nginx: [emerg] invalid parameter "https2" in /etc/nginx/sites-enabled/default-ssl.conf:3
nginx        | 2018-04-26 10:40:59,573 INFO exited: nginx (exit status 1; not expected)
nginx        | 2018-04-26 10:41:00,575 INFO gave up: nginx entered FATAL state, too many start retries too quickly

Why I have this problem ?

**Comment by ciarans** [comment]
@Creaprog there  is a typo - in default-ssl.conf you need to change it to 

```nginx
listen 443 ssl http2;

listen [::]:443 ssl http2 ipv6only=on;
```
