### ISSUE TITLE
/usr/local/etc/php no php.ini file

### ISSUE THREAD

**Issue by laurencefass** [richarvey/nginx-php-fpm#237]
im having problems with a 504 gateway timeout so I want to make changes to php.... and phpinfo(); says there's a php.ini file at /usr/local/etc/php but the directory is empty. i assume that php is being initialised from somewhere. any insights much appreciated.

thanks

**Comment by hundan2020** [comment]
I just ran into this problem, and then I tried to look for it, and I could do it by editing '/usr/local/etc/php/conf.d/docker-vars.ini ', and then after I ' pkill php-fpm ', the process automatically restarted, The configuration was successfully enforced.
