### ISSUE TITLE
2.2.1 and 3.0.1 images

### ISSUE THREAD

**Issue by dormancygrace** [richarvey/nginx-php-fpm#279]
Please, can you push this images?

**Comment by richarvey** [comment]
will push 3.0.1 shortly, just rolling up fixes now. as for 2.2.1 it failed to build so I'm dropping that

**Comment by dormancygrace** [comment]
> will push 3.0.1 shortly, just rolling up fixes now. as for 2.2.1 it failed to build so I'm dropping that

Maybe 2.2.0, then?
