### ISSUE TITLE
Freetype not supported by gd extension

### ISSUE THREAD

**Issue by zakov2302** [richarvey/nginx-php-fpm#280]
Should I re-configure gd?

**Comment by richarvey** [comment]
Just working on a fix 3.1.2

**Comment by richarvey** [comment]
This "should" work. Can you share the code which throws the error please. phpinfo() shows it should be enabled,


GD Support	enabled
GD Version	bundled (2.1.0 compatible)
FreeType Support	enabled
FreeType Linkage	with freetype
FreeType Version	2.12.1

**Comment by zakov2302** [comment]
sure.
PHP Version 8.1.6
GD Support enabled
GD Version  bundled (2.1.0 compatible)
GIF Read Support enabled
GIF Create Support enabled
PNG Support enabled
libPNG Version 1.6.37
WBMP Support enabled
XBM Support enabled
BMP Support enabled
TGA Read Support enabled

with mews/captcha to genarate captcha,  
Fatal error: Call to undefined function imagettftext()

**Comment by richarvey** [comment]
Try pulling a newer container version, it should be supported in the PHP 8.2.4 container.

**Comment by zakov2302** [comment]
Thank you.
