### ISSUE TITLE
Mongo DB Support

### ISSUE THREAD

**Issue by vicdvp** [richarvey/nginx-php-fpm#281]
How would I add MongoDB plugins for PHP? I've got the docker image running and tried installing 2 different ways via the command line of the nginx-php-fpm container itself.

1. I've tried adding as per the documentation on PHP Modules using `docker-php-ext-configure` but that doesn't work (error - Possible values for ext-name and mongodb's not in the list)

2. I also tried the `pecl install mongodb` method but that also didn't work (Cannot find autoconf and phpize failed)

Would I have to add the pecl method to the Dockerfile the same way you add redis and xdebug and build a new image?

**Comment by richarvey** [comment]
I'll have a go at this and let you know asap.

**Comment by richarvey** [comment]
I'm adding support for this in version 3.1.3

**Comment by vicdvp** [comment]
Thank you so much. I've downloaded and tested connecting and reading from both remote (MongoDB Atlas) and local (Docker instance) and it works perfectly.
