### ISSUE TITLE
where do i change the value of php.ini from dockerfile?

### ISSUE THREAD

**Issue by mrfzy00** [richarvey/nginx-php-fpm#294]
i manage to setup the version image of 3.1.6, after that i got some error cause to the memory heap of symfony needs more than 300mb

where do i find this config inside the container?

**Comment by idem84** [comment]
you can change php.ini settings via .htaccess or php (see ini_set('memory_limit', '-1');)

**Comment by mrfzy00** [comment]
thanks, it works
